### ISSUE TITLE
Support for subscriptions

### ISSUE THREAD

**Issue by rowlandekemezie** [linearapp/linear#22]
We're currently planning on integrating to linear as one of the services we support at GitStart, and we're curious if the API support subscription. If it doesn't,  is that currently in the roadmap

**Comment by jorilallo** [comment]
Subscriptions aren't on the roadmap but you can subscribe to webhooks to get realtime updates https://newsletter.linear.app/issues/linear-changelog-webhooks-markdown-sub-issue-improvements-222646
